version: '3'

services:
 mongo:
   image: mongo:3.2
   ports:
     - "27016:27017"
   command: --nojournal
   networks:
     fiwareNetwork:
       aliases:
         - mongo
   volumes:
     - "./data/db:/data/db"

 orion:
   image: fiware/orion
   ports:
     - "1026:1026"
   command:
     -dbhost mongo
     -corsOrigin __ALL
   networks:
     fiwareNetwork:
       aliases:
         - orion
   depends_on:
     - mongo

 iotagent:
   image: iotagent
   ports:
     - "5683:5683/udp"
   volumes:
     - "./config.js:/opt/iota-lwm2m/config.js"
   networks:
     fiwareNetwork:
       aliases:
         - iotagent
   depends_on:
     - mongo
     - orion

 cygnus:
   image: fiware/cygnus-ngsi
   ports: 
     - "8081:8081"
   volumes: 
     - "./agent.conf:/opt/apache-flume/conf/agent.conf"
   networks:
     fiwareNetwork:
       aliases:
         - cygnus
   depends_on:
     - mongo

 sth:
   image: telefonicaiot/fiware-sth-comet
   ports:
     - "8666:8666"
   environment:
     - STH_HOST=0.0.0.0
     - DB_URI=mongo:27017
   networks:
     fiwareNetwork:
       aliases:
         - sth
   depends_on:
     - mongo

 quantumleap:
   image: smartsdk/quantumleap
   ports:
     - "8668:8668"
   depends_on:
     - mongo
     - orion
     - crate
   environment:
     - CRATE_HOST=crate
   networks:
     fiwareNetwork:
       aliases:
         - quantumleap

 crate:
   image: crate:1.0.5
   ports:
     - "4200:4200"
     - "4300:4300"
   command: -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
   networks:
     fiwareNetwork:
       aliases:
         - crate

 grafana:
   image: grafana/grafana
   ports:
     - "3000:3000"
   environment:
     - GF_INSTALL_PLUGINS=crate-datasource,grafana-clock-panel,grafana-worldmap-panel
   depends_on:
     - crate
   networks:
     fiwareNetwork:
       aliases:
         - grafana

networks:
  fiwareNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/28

